In [5]:
import numpy as np
from numpy.random import randn

In [7]:
np.set_printoptions(precision=2)

In [9]:
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [15]:
b=np.array([
    [10,20,30],
    [ 40,50,60]
])
b

array([[10, 20, 30],
       [40, 50, 60]])

In [21]:
np.random.seed(25)
c=36*randn(6)
c

array([  8.22,  36.97, -30.23, -21.28, -34.45,  -8.  ])

In [23]:
d=np.arange(1,35)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [ ]:
#===========================
# OPERAÇÃO BÁSICA EM ARRAYS
#===========================

In [25]:
a*10

array([10, 20, 30, 40, 50, 60])

In [29]:
c+a

array([  9.22,  38.97, -27.23, -17.28, -29.45,  -2.  ])

In [31]:
c-a

array([  7.22,  34.97, -33.23, -25.28, -39.45, -14.  ])

In [33]:
c*a

array([   8.22,   73.94,  -90.68,  -85.13, -172.24,  -48.02])

In [35]:
c/a

array([  8.22,  18.48, -10.08,  -5.32,  -6.89,  -1.33])

In [39]:
a**2

array([ 1,  4,  9, 16, 25, 36])

In [ ]:
#===========================
# ALGEBRA LINEAR BÁSICA
#===========================

In [41]:
a = np.array([
    [2,4,6],
    [1,3,5],
    [10,20,30]
])
a

array([[ 2,  4,  6],
       [ 1,  3,  5],
       [10, 20, 30]])

In [43]:
b = np.array([
    [0,1,2],
    [3,4,5],
    [6,7,8]
])
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [45]:
a*b

array([[  0,   4,  12],
       [  3,  12,  25],
       [ 60, 140, 240]])

In [49]:
b/a

array([[0.  , 0.25, 0.33],
       [3.  , 1.33, 1.  ],
       [0.6 , 0.35, 0.27]])

In [51]:
np.dot(a,b)

array([[ 48,  60,  72],
       [ 39,  48,  57],
       [240, 300, 360]])